# Generated by Django 5.2 on 2025-04-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educamp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiofile",
            name="qa_pairs",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audiofile",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="audiofile",
            name="text_file_path",
            field=models.CharField(blank=True, default="", max_length=500),
            preserve_default=False,
        ),
    ]
