# Generated by Django 5.2 on 2025-04-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educamp", "0002_audiofile_qa_pairs_audiofile_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiofile",
            name="duration_sec",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
